import { stringify, parse } from 'yaml';

const GENERATED_HEADER = [
  '# Generated by pipeline-gen — https://github.com/NickSanft/pipeline-gen',
  '# Do not edit manually. Re-run `pipeline-gen generate` to update.',
  '',
].join('\n');

/** Serialize a value to YAML, prepending the generated-by header */
export function toYaml(value: unknown): string {
  return GENERATED_HEADER + stringify(value, { lineWidth: 120 });
}

/** Parse a YAML string */
export function fromYaml(content: string): unknown {
  return parse(content);
}
