import { describe, it, expect } from 'vitest';
import { join } from 'node:path';
import { analyzeRepo } from '../../src/analyzers/registry.js';
import { generatePipeline } from '../../src/generators/registry.js';
import { GithubActionsRenderer } from '../../src/renderers/github-actions.js';
import { fromYaml } from '../../src/utils/yaml.js';

const FIXTURES = join(import.meta.dirname, '../fixtures');
const renderer = new GithubActionsRenderer();

async function renderFixture(fixture: string): Promise<string> {
  const manifest = await analyzeRepo(join(FIXTURES, fixture));
  return renderer.render(generatePipeline(manifest));
}

// ── Snapshot tests ────────────────────────────────────────────────────────────

describe('GithubActionsRenderer snapshots', () => {
  it('renders node-basic', async () => {
    expect(await renderFixture('node-basic')).toMatchSnapshot();
  });

  it('renders python-fastapi', async () => {
    expect(await renderFixture('python-fastapi')).toMatchSnapshot();
  });

  it('renders go-service', async () => {
    expect(await renderFixture('go-service')).toMatchSnapshot();
  });
});

// ── Structural assertions ─────────────────────────────────────────────────────

describe('GithubActionsRenderer structure', () => {
  it('produces valid YAML that parses correctly', async () => {
    const yaml = await renderFixture('node-basic');
    // Strip the header comment before parsing
    const body = yaml.split('\n').filter((l) => !l.startsWith('#')).join('\n');
    expect(() => fromYaml(body)).not.toThrow();
  });

  it('includes the generated-by header comment', async () => {
    const yaml = await renderFixture('node-basic');
    expect(yaml).toContain('Generated by pipeline-gen');
  });

  it('sets permissions: read-all at workflow level', async () => {
    const yaml = await renderFixture('node-basic');
    expect(yaml).toContain('permissions: read-all');
  });

  it('all uses: lines are SHA-pinned (40-char hex, no mutable tags)', async () => {
    for (const fixture of ['node-basic', 'python-fastapi', 'go-service']) {
      const yaml = await renderFixture(fixture);
      const usesLines = yaml.split('\n').filter((l) => /^\s+uses:/.test(l));
      expect(usesLines.length, `${fixture} has no uses: lines`).toBeGreaterThan(0);
      for (const line of usesLines) {
        const sha = line.split('@')[1]?.trim();
        expect(sha, `line: ${line.trim()}`).toMatch(/^[0-9a-f]{40}$/);
      }
    }
  });

  it('injects an actions/cache step after checkout for node-basic', async () => {
    const yaml = await renderFixture('node-basic');
    const lines = yaml.split('\n');
    const checkoutIdx = lines.findIndex((l) => l.includes('actions/checkout@'));
    const cacheIdx = lines.findIndex((l) => l.includes('actions/cache@'));
    expect(checkoutIdx).toBeGreaterThan(-1);
    expect(cacheIdx).toBeGreaterThan(checkoutIdx);
  });

  it('injects an actions/cache step for go-service', async () => {
    const yaml = await renderFixture('go-service');
    expect(yaml).toContain('actions/cache@');
  });

  it('emits needs: for dependent stages', async () => {
    const yaml = await renderFixture('node-basic');
    // build stage should declare needs: [unit-tests]
    expect(yaml).toMatch(/needs:\s*\n\s*- unit-tests/);
  });

  it('emits strategy.matrix for node LTS matrix', async () => {
    const yaml = await renderFixture('node-basic');
    expect(yaml).toContain('node-version:');
    expect(yaml).toContain('- "20"');
    expect(yaml).toContain('- "22"');
  });

  it('emits strategy.matrix for python version matrix', async () => {
    const yaml = await renderFixture('python-fastapi');
    expect(yaml).toContain('python-version:');
    expect(yaml).toContain('- "3.10"');
    expect(yaml).toContain('- "3.12"');
  });

  it('includes gitleaks secret scanning step', async () => {
    for (const fixture of ['node-basic', 'python-fastapi', 'go-service']) {
      const yaml = await renderFixture(fixture);
      expect(yaml, fixture).toContain('gitleaks/gitleaks-action@');
    }
  });

  it('outputs to .github/workflows/', async () => {
    const manifest = await analyzeRepo(join(FIXTURES, 'node-basic'));
    const pipeline = generatePipeline(manifest);
    const path = renderer.outputPath(pipeline);
    expect(path).toMatch(/^\.github\/workflows\/.+\.yml$/);
  });

  it('produces correct output path for node-basic', async () => {
    const manifest = await analyzeRepo(join(FIXTURES, 'node-basic'));
    const pipeline = generatePipeline(manifest);
    expect(renderer.outputPath(pipeline)).toBe('.github/workflows/node-basic-ci.yml');
  });
});
